name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM1
      run: |
        ssh thienly@20.2.114.34 << 'EOF'
          cd /home/thienly/web-project-2024-ui-client
          sudo rm -rf build/*
          cp -r build/* /home/thienly/web-project-2024-ui-client/build
          sudo systemctl restart nginx
        EOF
